Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -33,6 +33,15 @@ jobs:
             find . -name '*.html'
           fi
 
+      - name: Check CSS files exist
+        run: |
+          if [ -z "$(find . -name '*.css')"]; then
+            echo "ERROR: No CSS Files found"
+            exit 1
+          else
+            echo "CSS Files found"
+          fi
+
   # This job only runs if the check job above passes
   deploy:
     needs: check
